image: docker:latest

services:
  - docker:dind

variables:
  AWS_REGION: "us-east-1"
  ECR_REGISTRY: "967823535579.dkr.ecr.us-east-1.amazonaws.com/my-java-app"
  ECR_REPOSITORY: "my-java-app"
  IMAGE_TAG: "latest"

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install awscli
  - aws --version
  - eval $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)

build:
  stage: build
  script:
    - echo "Building JAR..."
    - ./mvnw clean package -DskipTests
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying to ECS..."
    - aws ecs update-service \
        --cluster my-java-app-cluster \
        --service my-java-app-service \
        --force-new-deployment \
        --region $AWS_REGION
