image: amazon/aws-cli:2.13.26  # ✅ Includes aws-cli pre-installed

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  AWS_REGION: "us-east-1"
  ECR_REGISTRY: "967823535579.dkr.ecr.us-east-1.amazonaws.com"
  ECR_REPOSITORY: "my-java-app"
  IMAGE_TAG: "latest"

stages:
  - build
  - deploy

before_script:
  # ✅ Install Docker CLI since amazon/aws-cli doesn't come with it
  - apk add --no-cache docker openjdk17 maven

build:
  stage: build
  script:
    - echo "Building JAR..."
    - ./mvnw clean package -DskipTests
    - echo "Logging into AWS ECR..."
    - aws --version
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - echo "Pushing image to ECR..."
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

deploy:
  image: amazon/aws-cli:2.13.26  # ✅ Again, aws-cli pre-installed
  stage: deploy
  script:
    - echo "Deploying to ECS..."
    - aws ecs update-service \
        --cluster my-java-app-cluster \
        --service my-java-app-service \
        --force-new-deployment \
        --region $AWS_REGION
