stages:
  - build
  - deploy

variables:
  AWS_REGION: "us-east-1"
  ECR_REGISTRY: "967823535579.dkr.ecr.us-east-1.amazonaws.com"
  ECR_REPOSITORY: "my-java-app"
  IMAGE_TAG: "latest"

build:
  image: maven:3.9-eclipse-temurin-17  # Java + Maven
  services:
    - docker:dind
  stage: build
  before_script:
    - echo "Using Java and Maven"
  script:
    - ./mvnw clean package -DskipTests
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - echo $AWS_ACCESS_KEY_ID | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

deploy:
  image: python:3.11-alpine
  stage: deploy
  before_script:
    - pip install --no-cache-dir awscli
  script:
    - aws ecs update-service \
        --cluster my-java-app-cluster \
        --service my-java-app-service \
        --force-new-deployment \
        --region $AWS_REGION
