image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  AWS_REGION: "us-east-1"  # Change if your region is different
  ECR_REGISTRY: "123456789012.dkr.ecr.us-east-1.amazonaws.com"  # Change this
  ECR_REPOSITORY: "my-java-app"
  IMAGE_TAG: "latest"

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache openjdk17 maven curl unzip
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip -q awscliv2.zip
  - ./aws/install
  - export PATH=$PATH:/usr/local/bin
  - aws --version
  - echo "Logging in to AWS ECR..."
  - aws sts get-caller-identity  # This confirms credentials are working
  - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

build:
  stage: build
  script:
    - echo "Building JAR..."
    - ./mvnw clean package -DskipTests
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

deploy:
  image: python:3.11-slim
  stage: deploy
  before_script:
    - pip install --no-cache-dir awscli
  script:
    - echo "Deploying to ECS..."
    - aws ecs update-service \
        --cluster my-java-app-cluster \
        --service my-java-app-service \
        --force-new-deployment \
        --region $AWS_REGION
